[build]
  publish = "instagram"

[[redirects]]
  from = "/try"
  to = "/try.html"
  status = 200

[[redirects]]
  from = "/thanks"
  to = "/thanks.html"
  status = 200

[[headers]]
  for = "/assets/video/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"
