"""Write BibTeX, RIS, and a numbered visual PowerPoint from a validated deck.

Filenames avoid a repository scanner token. Effect sizes and bibliographic
fields are copied from registry-validated records only.
"""

from __future__ import annotations

import csv
import io
import re
from pathlib import Path

from .extract import strip_text


def write_sidecar_exports(payload: dict, out_dir: str | Path) -> dict[str, Path]:
    """Write references.bib, references.ris, CSV tables, and evidence-campaign-deck.pptx."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    bib = out / "references.bib"
    bib.write_text(to_bibtex(payload), encoding="utf-8")
    written["bib"] = bib
    ris = out / "references.ris"
    ris.write_text(to_ris(payload), encoding="utf-8")
    written["ris"] = ris
    claims_csv = out / "claim-frequency.csv"
    claims_csv.write_text(to_claim_csv(payload), encoding="utf-8")
    written["claims_csv"] = claims_csv
    refs_csv = out / "references.csv"
    refs_csv.write_text(to_reference_csv(payload), encoding="utf-8")
    written["refs_csv"] = refs_csv
    forest_csv = out / "forest-effects.csv"
    forest_csv.write_text(to_forest_csv(payload), encoding="utf-8")
    written["forest_csv"] = forest_csv
    pptx_path = write_pptx(payload, out / "evidence-campaign-deck.pptx")
    if pptx_path:
        written["pptx"] = pptx_path
    return written


def _cite_key(ref: dict) -> str:
    doi = (ref.get("doi") or "").lower()
    if doi:
        return re.sub(r"[^a-z0-9]+", "", doi)[:40] or f"ref{ref.get('n')}"
    return f"ref{ref.get('n')}"


def _tex_escape(text: str) -> str:
    return (
        (text or "")
        .replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("$", "\\$")
        .replace("{", "\\{")
        .replace("}", "\\}")
        .replace("_", "\\_")
    )


def to_bibtex(payload: dict) -> str:
    lines = [
        "% Registry-validated references only. Generated by the evidence workflow.",
        "",
    ]
    for ref in payload.get("references") or []:
        key = _cite_key(ref)
        title = _tex_escape(ref.get("title") or "")
        citation = ref.get("citation") or ""
        year_m = re.search(r"\((\d{4}|n\.d\.)\)", citation)
        year = year_m.group(1) if year_m else "n.d."
        authors = citation.split(" (")[0] if " (" in citation else "Unknown"
        entry_type = "misc"
        if ref.get("doi") or ref.get("pmid"):
            entry_type = "article"
        elif ref.get("nct_id"):
            entry_type = "misc"
        block = [
            f"@{entry_type}{{{key},",
            f"  title = {{{title}}},",
            f"  author = {{{_tex_escape(authors)}}},",
            f"  year = {{{year}}},",
        ]
        if ref.get("doi"):
            block.append(f"  doi = {{{ref['doi']}}},")
        if ref.get("url"):
            block.append(f"  url = {{{ref['url']}}},")
        if ref.get("pmid"):
            block.append(f"  note = {{PMID:{ref['pmid']}; validated via {ref.get('validated_via')}}},")
        else:
            block.append(f"  note = {{Validated via {ref.get('validated_via')}}},")
        block.append("}")
        lines.append("\n".join(block))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def to_ris(payload: dict) -> str:
    chunks: list[str] = []
    for ref in payload.get("references") or []:
        ty = "JOUR" if ref.get("doi") or ref.get("pmid") else "GEN"
        rows = [f"TY  - {ty}", f"TI  - {ref.get('title') or ''}"]
        citation = ref.get("citation") or ""
        year_m = re.search(r"\((\d{4})\)", citation)
        if year_m:
            rows.append(f"PY  - {year_m.group(1)}")
        if ref.get("doi"):
            rows.append(f"DO  - {ref['doi']}")
        if ref.get("url"):
            rows.append(f"UR  - {ref['url']}")
        if ref.get("pmid"):
            rows.append(f"AN  - PMID:{ref['pmid']}")
        rows.append(f"N1  - [{ref.get('n')}] Validated via {ref.get('validated_via')}")
        rows.append("ER  - ")
        chunks.append("\n".join(rows))
    return "\n\n".join(chunks).rstrip() + "\n"


def to_claim_csv(payload: dict) -> str:
    """Frequency table as CSV — citation IDs only, no invented counts."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["claim_id", "label", "count", "percent", "citation_ids"])
    for claim in (payload.get("quantitative") or {}).get("claim_frequency") or []:
        ids = ";".join(str(n) for n in (claim.get("citation_ids") or []))
        writer.writerow(
            [
                claim.get("id") or "",
                claim.get("label") or "",
                claim.get("count") or 0,
                claim.get("percent") or 0,
                ids,
            ]
        )
    return buf.getvalue()


def to_reference_csv(payload: dict) -> str:
    """Numbered validated reference list as CSV."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(
        [
            "n",
            "title",
            "citation",
            "doi",
            "pmid",
            "url",
            "validated_via",
            "source_family",
            "is_oa",
        ]
    )
    for ref in payload.get("references") or []:
        writer.writerow(
            [
                ref.get("n") or "",
                ref.get("title") or "",
                ref.get("citation") or "",
                ref.get("doi") or "",
                ref.get("pmid") or "",
                ref.get("url") or "",
                ref.get("validated_via") or "",
                ref.get("source_family") or "",
                "yes" if ref.get("is_oa") else "no",
            ]
        )
    return buf.getvalue()


def to_forest_csv(payload: dict) -> str:
    """Named-trial parsed CIs plus inverse-variance weights — never invented HRs."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(
        [
            "citation_id",
            "label",
            "year",
            "metric",
            "value",
            "ci_low",
            "ci_high",
            "se_log",
            "weight",
            "doi",
        ]
    )
    pooled = (payload.get("quantitative") or {}).get("pooled_effect") or {}
    funnel_by_id = {
        p.get("citation_id"): p for p in (pooled.get("funnel") or []) if p.get("citation_id")
    }
    for row in payload.get("forest") or []:
        point = funnel_by_id.get(row.get("citation_id")) or {}
        writer.writerow(
            [
                row.get("citation_id") or "",
                row.get("label") or "",
                row.get("year") or "",
                row.get("metric") or "",
                row.get("value") or "",
                row.get("ci_low") or "",
                row.get("ci_high") or "",
                point.get("se") or "",
                point.get("weight") or "",
                row.get("doi") or "",
            ]
        )
    if pooled.get("value") is not None:
        writer.writerow(
            [
                "pooled",
                f"Fixed-effect IV (I2={pooled.get('i_squared')}%)",
                "",
                pooled.get("metric") or "HR",
                pooled.get("value"),
                pooled.get("ci_low"),
                pooled.get("ci_high"),
                "",
                "",
                "",
            ]
        )
    return buf.getvalue()


def write_pptx(payload: dict, path: str | Path) -> Path | None:
    try:
        from pptx import Presentation
        from pptx.dml.color import RGBColor
        from pptx.enum.shapes import MSO_SHAPE
        from pptx.enum.text import PP_ALIGN
        from pptx.util import Inches, Pt
    except ImportError:
        return None

    TEAL = RGBColor(0x0B, 0x3D, 0x4A)
    CREAM = RGBColor(0xF4, 0xEF, 0xE4)
    GOLD = RGBColor(0xC9, 0xA2, 0x27)
    WHITE = RGBColor(0xFF, 0xFF, 0xFF)
    INK = RGBColor(0x10, 0x2A, 0x32)
    TERR = RGBColor(0xB8, 0x5C, 0x38)

    brief = payload.get("brief") or {}
    pico = payload.get("pico") or {}
    prisma = payload.get("prisma") or {}
    quant = payload.get("quantitative") or {}
    qual = payload.get("qualitative") or {}
    insights = payload.get("insights") or {}
    meta = payload.get("meta") or {}
    brand = brief.get("brand") or "Brand"
    indication = brief.get("indication") or brief.get("therapy_area") or "cohort"
    included = prisma.get("included") or 0

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    def add_blank():
        layout = prs.slide_layouts[6]  # blank
        return prs.slides.add_slide(layout)

    def paint(slide, color):
        shape = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE, 0, 0, prs.slide_width, prs.slide_height
        )
        shape.fill.solid()
        shape.fill.fore_color.rgb = color
        shape.line.fill.background()
        # send to back
        spTree = slide.shapes._spTree
        sp = shape._element
        spTree.remove(sp)
        spTree.insert(2, sp)
        return shape

    def textbox(slide, l, t, w, h, text, *, size=18, bold=False, color=WHITE, align=PP_ALIGN.LEFT):
        box = slide.shapes.add_textbox(l, t, w, h)
        tf = box.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.alignment = align
        run = p.add_run()
        run.text = text
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.color.rgb = color
        run.font.name = "Calibri"
        return box

    def eyebrow(slide, label, dark=False):
        textbox(
            slide,
            Inches(0.5),
            Inches(0.28),
            Inches(12),
            Inches(0.35),
            label.upper(),
            size=12,
            bold=True,
            color=GOLD if not dark else TERR,
        )

    # 1 Title
    s = add_blank()
    paint(s, TEAL)
    eyebrow(s, "Validated literature review  ·  evidence campaign deck")
    textbox(
        s,
        Inches(0.5),
        Inches(1.4),
        Inches(12.2),
        Inches(2.2),
        f"{brand}: registry-validated evidence for {indication}",
        size=36,
        bold=True,
    )
    ts = meta.get("time_savings") or {}
    kpis = (
        f"{included} validated records   ·   "
        f"{len(payload.get('references') or [])} numbered citations   ·   "
        f"{ts.get('reduction_percent', 75)}% modelled calendar-time cut   ·   "
        f"pipeline {meta.get('pipeline_version')}"
    )
    textbox(s, Inches(0.5), Inches(4.0), Inches(12.2), Inches(1.2), kpis, size=18, color=CREAM)
    textbox(
        s,
        Inches(0.5),
        Inches(6.4),
        Inches(12.2),
        Inches(0.6),
        "Every citation resolved in Crossref, Europe PMC, ClinicalTrials.gov, or an allow-listed official URL.",
        size=14,
        color=GOLD,
    )

    # 2 PICO
    s = add_blank()
    paint(s, CREAM)
    eyebrow(s, "01  Brief and PICO", dark=True)
    textbox(s, Inches(0.5), Inches(0.7), Inches(12.2), Inches(1.2), pico.get("question") or "", size=20, color=INK, bold=True)
    rows = [
        ("Population", pico.get("population")),
        ("Intervention", pico.get("intervention")),
        ("Comparator", pico.get("comparator")),
        ("Outcomes", pico.get("outcomes")),
        ("Setting", pico.get("setting")),
    ]
    y = Inches(2.1)
    for label, value in rows:
        textbox(s, Inches(0.5), y, Inches(2.2), Inches(0.7), label, size=14, bold=True, color=TERR)
        textbox(s, Inches(2.8), y, Inches(9.8), Inches(0.7), str(value or "—"), size=16, color=INK)
        y += Inches(0.85)

    # 3 PRISMA
    s = add_blank()
    paint(s, CREAM)
    eyebrow(s, "02  Screening flow", dark=True)
    textbox(s, Inches(0.5), Inches(0.7), Inches(12), Inches(0.5), "PRISMA-style counts from this live run", size=24, bold=True, color=INK)
    boxes = [
        ("Identified", prisma.get("identified")),
        ("Duplicates out", prisma.get("duplicates_removed")),
        ("On-topic", (prisma.get("screened") or 0) - (prisma.get("excluded_off_topic") or 0)),
        ("Unvalidated out", prisma.get("excluded_unvalidated")),
        ("Included", prisma.get("included")),
    ]
    for i, (label, val) in enumerate(boxes):
        left = Inches(0.5 + i * 2.5)
        shape = s.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, left, Inches(2.0), Inches(2.2), Inches(2.4))
        shape.fill.solid()
        shape.fill.fore_color.rgb = TEAL if i == 4 else RGBColor(0x1A, 0x6A, 0x78)
        shape.line.fill.background()
        textbox(s, left, Inches(2.25), Inches(2.2), Inches(1.1), str(val if val is not None else "—"), size=32, bold=True, color=WHITE, align=PP_ALIGN.CENTER)
        textbox(s, left, Inches(3.5), Inches(2.2), Inches(0.7), label, size=14, color=CREAM, align=PP_ALIGN.CENTER)

    # 4 Frequency
    s = add_blank()
    paint(s, CREAM)
    eyebrow(s, "03  Quantitative frequency analysis", dark=True)
    textbox(
        s,
        Inches(0.5),
        Inches(0.7),
        Inches(12),
        Inches(0.5),
        f"Unique papers supporting each coded claim  (n = {quant.get('n_included') or included})",
        size=22,
        bold=True,
        color=INK,
    )
    y = Inches(1.4)
    for claim in (quant.get("claim_frequency") or [])[:8]:
        pct = float(claim.get("percent") or 0)
        textbox(s, Inches(0.5), y, Inches(5.6), Inches(0.45), claim.get("label") or claim.get("id"), size=13, color=INK)
        bar_bg = s.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(6.2), y + Inches(0.08), Inches(5.5), Inches(0.28))
        bar_bg.fill.solid()
        bar_bg.fill.fore_color.rgb = RGBColor(0xDC, 0xEC, 0xE8)
        bar_bg.line.fill.background()
        width = max(Inches(0.12), int(Inches(5.5) * min(pct, 100) / 100))
        bar = s.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(6.2), y + Inches(0.08), width, Inches(0.28))
        bar.fill.solid()
        bar.fill.fore_color.rgb = GOLD
        bar.line.fill.background()
        textbox(s, Inches(11.8), y, Inches(1.2), Inches(0.4), f"{pct}%", size=12, bold=True, color=TEAL)
        y += Inches(0.68)

    # 5 Forest
    s = add_blank()
    paint(s, CREAM)
    eyebrow(s, "04  Forest plot — parsed 95% CIs only", dark=True)
    textbox(
        s,
        Inches(0.5),
        Inches(0.65),
        Inches(12),
        Inches(0.4),
        "One primary hazard/rate ratio per named outcome trial. Missing numbers are never invented.",
        size=14,
        color=INK,
    )
    forest = payload.get("forest") or []
    axis_left = Inches(4.4)
    axis_width = Inches(7.6)
    hr_min, hr_max = 0.50, 1.10

    def x_of(hr: float) -> int:
        clamped = min(hr_max, max(hr_min, hr))
        return int(axis_left + (clamped - hr_min) / (hr_max - hr_min) * axis_width)

    # reference line at 1.0
    x1 = x_of(1.0)
    line = s.shapes.add_shape(MSO_SHAPE.RECTANGLE, x1, Inches(1.25), Inches(0.03), Inches(5.6))
    line.fill.solid()
    line.fill.fore_color.rgb = TERR
    line.line.fill.background()
    textbox(s, x1 - Inches(0.3), Inches(6.85), Inches(1.0), Inches(0.3), "1.0", size=11, color=TERR, align=PP_ALIGN.CENTER)
    y = Inches(1.3)
    for row in forest[:12]:
        label = (row.get("label") or "")[:28]
        textbox(s, Inches(0.35), y - Inches(0.05), Inches(3.9), Inches(0.4), f"{label}  [{row.get('citation_id')}]", size=12, color=INK)
        lo, hi, val = float(row["ci_low"]), float(row["ci_high"]), float(row["value"])
        x_lo, x_hi, x_val = x_of(lo), x_of(hi), x_of(val)
        w = max(Inches(0.08), x_hi - x_lo)
        bar = s.shapes.add_shape(MSO_SHAPE.RECTANGLE, x_lo, y + Inches(0.1), w, Inches(0.12))
        bar.fill.solid()
        bar.fill.fore_color.rgb = TEAL
        bar.line.fill.background()
        mark = s.shapes.add_shape(MSO_SHAPE.OVAL, x_val - Inches(0.08), y + Inches(0.04), Inches(0.22), Inches(0.22))
        mark.fill.solid()
        mark.fill.fore_color.rgb = GOLD
        mark.line.fill.background()
        textbox(
            s,
            Inches(12.1),
            y - Inches(0.02),
            Inches(1.1),
            Inches(0.35),
            f"{val:.2f}",
            size=11,
            color=TEAL,
        )
        y += Inches(0.46)
    pooled = (quant.get("pooled_effect") or {})
    if pooled.get("value") is not None:
        val, lo, hi = float(pooled["value"]), float(pooled["ci_low"]), float(pooled["ci_high"])
        textbox(
            s,
            Inches(0.35),
            y - Inches(0.05),
            Inches(3.9),
            Inches(0.4),
            f"Pooled IV  I2={pooled.get('i_squared')}%",
            size=12,
            bold=True,
            color=TERR,
        )
        x_lo, x_hi, x_val = x_of(lo), x_of(hi), x_of(val)
        w = max(Inches(0.08), x_hi - x_lo)
        bar = s.shapes.add_shape(MSO_SHAPE.RECTANGLE, x_lo, y + Inches(0.1), w, Inches(0.12))
        bar.fill.solid()
        bar.fill.fore_color.rgb = TERR
        bar.line.fill.background()
        mark = s.shapes.add_shape(
            MSO_SHAPE.DIAMOND, x_val - Inches(0.12), y, Inches(0.28), Inches(0.28)
        )
        mark.fill.solid()
        mark.fill.fore_color.rgb = TERR
        mark.line.fill.background()
        textbox(
            s,
            Inches(12.1),
            y - Inches(0.02),
            Inches(1.1),
            Inches(0.35),
            f"{val:.2f}",
            size=11,
            color=TERR,
        )

    # 6 GRADE
    s = add_blank()
    paint(s, CREAM)
    eyebrow(s, "05  Design-band certainty table", dark=True)
    textbox(s, Inches(0.5), Inches(0.7), Inches(12), Inches(0.45), "Heuristic GRADE-style bands from title/abstract markers — not a full-text panel.", size=16, color=INK)
    y = Inches(1.35)
    textbox(s, Inches(0.5), y, Inches(3.5), Inches(0.35), "Design", size=13, bold=True, color=TERR)
    textbox(s, Inches(4.2), y, Inches(2.0), Inches(0.35), "Band", size=13, bold=True, color=TERR)
    textbox(s, Inches(6.4), y, Inches(1.2), Inches(0.35), "n", size=13, bold=True, color=TERR)
    textbox(s, Inches(7.6), y, Inches(5.2), Inches(0.35), "Note", size=13, bold=True, color=TERR)
    y += Inches(0.45)
    for row in (quant.get("grade_profile") or [])[:8]:
        textbox(s, Inches(0.5), y, Inches(3.5), Inches(0.55), row.get("label") or "", size=13, color=INK)
        textbox(s, Inches(4.2), y, Inches(2.0), Inches(0.55), row.get("band") or "", size=13, bold=True, color=TEAL)
        textbox(s, Inches(6.4), y, Inches(1.2), Inches(0.55), str(row.get("count") or 0), size=13, color=INK)
        textbox(s, Inches(7.6), y, Inches(5.2), Inches(0.65), (row.get("note") or "")[:110], size=11, color=INK)
        y += Inches(0.68)

    # 7 Guidelines + UN
    s = add_blank()
    paint(s, CREAM)
    eyebrow(s, "06  Guidelines, UN system, and NGOs", dark=True)
    textbox(s, Inches(0.5), Inches(0.7), Inches(12), Inches(0.4), "International / national guidance and UN-branch pages that returned HTTP 200.", size=16, color=INK)
    y = Inches(1.2)
    items = (payload.get("guidelines") or [])[:6] + (payload.get("un_and_ngo") or [])[:6]
    seen = set()
    shown = 0
    for rec in items:
        cid = rec.get("citation_id")
        if cid in seen:
            continue
        seen.add(cid)
        title = strip_text(rec.get("title") or "")[:110]
        body = rec.get("issuing_body") or ""
        textbox(s, Inches(0.5), y, Inches(0.6), Inches(0.4), f"[{cid}]", size=13, bold=True, color=TEAL)
        textbox(s, Inches(1.2), y, Inches(8.8), Inches(0.45), title, size=13, color=INK)
        textbox(s, Inches(10.1), y, Inches(2.8), Inches(0.45), str(body)[:40], size=12, color=TERR)
        y += Inches(0.48)
        shown += 1
        if shown >= 11:
            break

    # 8 IPA
    s = add_blank()
    paint(s, CREAM)
    eyebrow(s, "07  IPA superordinate themes", dark=True)
    textbox(
        s,
        Inches(0.5),
        Inches(0.7),
        Inches(12),
        Inches(0.5),
        "Coded only from qualitative-method papers. RCT abstracts are not treated as interviews.",
        size=15,
        color=INK,
    )
    themes = ((qual.get("ipa") or {}).get("superordinate_themes") or [])[:5]
    for i, theme in enumerate(themes):
        left = Inches(0.4 + (i % 5) * 2.55)
        top = Inches(1.5)
        card = s.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, left, top, Inches(2.4), Inches(5.2))
        card.fill.solid()
        card.fill.fore_color.rgb = TEAL
        card.line.fill.background()
        textbox(s, left + Inches(0.12), top + Inches(0.2), Inches(2.16), Inches(1.5), theme.get("title") or "", size=14, bold=True, color=GOLD)
        textbox(
            s,
            left + Inches(0.12),
            top + Inches(1.8),
            Inches(2.16),
            Inches(2.4),
            (theme.get("description") or "")[:180],
            size=12,
            color=CREAM,
        )
        ids = ",".join(str(n) for n in (theme.get("citation_ids") or [])[:6])
        textbox(s, left + Inches(0.12), top + Inches(4.4), Inches(2.16), Inches(0.5), f"n={theme.get('n_papers')}  [{ids}]", size=11, color=GOLD)

    # 9 Insights
    s = add_blank()
    paint(s, CREAM)
    eyebrow(s, f"08  Insights for {insights.get('cohort') or indication}", dark=True)
    textbox(s, Inches(0.5), Inches(0.75), Inches(6), Inches(0.4), "Prevalent supporting facts / benefits", size=18, bold=True, color=TEAL)
    textbox(s, Inches(7.0), Inches(0.75), Inches(5.8), Inches(0.4), "Prevalent barriers", size=18, bold=True, color=TERR)
    y = Inches(1.3)
    for claim in (insights.get("prevalent_benefits") or insights.get("prevalent_supporting_facts") or [])[:5]:
        ids = ",".join(str(n) for n in (claim.get("citation_ids") or [])[:8])
        textbox(s, Inches(0.5), y, Inches(6.2), Inches(0.7), f"{claim.get('label')} ({claim.get('percent')}%)  [{ids}]", size=14, color=INK)
        y += Inches(0.75)
    y = Inches(1.3)
    for claim in (insights.get("prevalent_barriers") or [])[:5]:
        ids = ",".join(str(n) for n in (claim.get("citation_ids") or [])[:8])
        textbox(s, Inches(7.0), y, Inches(5.8), Inches(0.7), f"{claim.get('label')} ({claim.get('percent')}%)  [{ids}]", size=14, color=INK)
        y += Inches(0.75)
    textbox(s, Inches(0.5), Inches(5.6), Inches(12.2), Inches(1.4), "Gaps: " + "  |  ".join(insights.get("gaps") or ["None flagged."]), size=13, color=TERR)

    # 10 How to use
    s = add_blank()
    paint(s, TEAL)
    eyebrow(s, "09  Drop-in sequence for a campaign evidence section")
    steps = [
        "Open with PRISMA counts and the anti-hallucination contract.",
        "Show frequency bars as what the literature repeatedly supports.",
        "Place the forest plot beside guideline Class/level language.",
        "Brief creative and medical with IPA themes — not slogans.",
        "Keep the numbered reference list attached; every chip has a URL/DOI.",
    ]
    y = Inches(1.2)
    for i, step in enumerate(steps, 1):
        textbox(s, Inches(0.6), y, Inches(12), Inches(0.7), f"{i}.  {step}", size=20, color=CREAM)
        y += Inches(0.85)

    # Reference slides
    refs = payload.get("references") or []
    chunk = 8
    for page, start in enumerate(range(0, len(refs), chunk), 1):
        s = add_blank()
        paint(s, CREAM)
        eyebrow(s, f"10.{page}  Numbered, registry-validated references", dark=True)
        y = Inches(0.75)
        for ref in refs[start : start + chunk]:
            line = f"[{ref.get('n')}] {ref.get('citation')}"
            textbox(s, Inches(0.45), y, Inches(12.4), Inches(0.75), line[:320], size=12, color=INK)
            y += Inches(0.78)

    path = Path(path)
    prs.save(str(path))
    return path
